// todo-app-with-vue/src/components/EditTodo.vue
<template>
  <section class="edit-form">

    <textarea id="edit-todo" v-model="todo.text"></textarea>

    <div>
      <button class="btn done" @click="confirmEditing">Done</button>
      <button class="btn cancel" @click="close">Cancel</button>
    </div>

  </section>
</template>

<script>
export default {
  name: 'EditTodo',
  props: ["todo"],
  methods:{
    confirmEditing(){
      if(this.todo.text.trim().length){
        this.$emit('edit', {text:this.todo.text.trim(), index: this.todo.index});
        this.close();
      }
    },
    close(){
      this.$emit('cancel')
    }
  }
}
</script>

<style scoped>
</style>

// todo-app-with-react/src/components/EditTodo.js
import {useState} from 'react';
const EditTodo = function({todo, closeForm, updateTodo}){
  let [todoObject, setTodo] = useState(todo || {});
  let handleChange = (e)=>{
    setTodo({todo: e.target.value, id: todoObject.id})
  }
  return(
    <section className="edit-form">
      <textarea id="edit-todo" value={todoObject.todo} onChange={handleChange}></textarea>
      <div>
        <button className="btn done" onClick={()=> updateTodo(todoObject.todo, todoObject.id)}>Done</button>
        <button className="btn cancel" onClick={closeForm}>Cancel</button>
      </div>
    </section>
  )
}
export default EditTodo
