// todo-app-with-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  todos: string[] = JSON.parse(localStorage.getItem('angular-todos')) || [];
  isEditFormOpend: Boolean = false;
  currentTodo = {todo: '', i: null}

  closeEditForm() {
    this.isEditFormOpend = false;
  }

  openEditForm(todo, i) {
    this.currentTodo = {todo, i};
    this.isEditFormOpend = true;
  }

  insertTodo(todo){
    this.todos = [...this.todos, todo];
    localStorage.setItem('angular-todos', JSON.stringify(this.todos))
  }

  EditTodo(todo){
    this.todos = this.todos.map((t, i)=> i == this.currentTodo.i ? todo : t);
    localStorage.setItem('angular-todos', JSON.stringify(this.todos))

    this.closeEditForm()
  }

  deleteTodo(i){
    this.todos = this.todos.filter((todo, index) => index != i);
    localStorage.setItem('angular-todos', JSON.stringify(this.todos))
  }
  title = 'todo-app-with-angular';
}

<h1 class="title">TODO APP</h1>
<section class="todos-container">
  <app-add-todo (addTodo)="insertTodo($event)"></app-add-todo>

  <div class="todos" *ngIf="todos[0]; then theretodos else notodos"></div>
  <ng-template #theretodos>
    <div class="todos">
      <app-todo *ngFor="let todo of todos; let i = index" [todo]="todo" [i]="i" (openEditing)="openEditForm(todo, i)" (deleteTheTodo)="deleteTodo(i)"></app-todo>
    </div>
  </ng-template>
  <ng-template #notodos>there are no todos yet</ng-template>

</section>

<app-update-todo *ngIf="isEditFormOpend" (canceleEditing)="closeEditForm()" (updateTodo)="EditTodo($event)" [todo]="currentTodo"></app-update-todo>

// todo-app-with-react/src/App.js
import Todo from './components/Todo.js';
import AddTodo from './components/AddTodo.js';
import EditTodo from './components/EditTodo.js';

import {useState} from 'react';

function App() {
  let [todos, setTodos] = useState(JSON.parse(localStorage.getItem('react-todo')) || []);
  let [isFormEditOpen, setFormEdit] = useState(false);
  let [currentTodo, setCurrentTodo] = useState({todo:'', id: ''});


  let addTodo = (e)=>{
    if(e.keyCode === 13){
      if(e.target.value.trim().length){
        localStorage.setItem('react-todo', JSON.stringify([...todos, e.target.value.trim()]))
        setTodos([...todos, e.target.value.trim()]);
        e.target.value = '';
      }
    }
  }


  let deleteTodo = (id) => {
    localStorage.setItem('react-todo', JSON.stringify(todos.filter((item, i) => i !== id)));
    setTodos(todos.filter((item, i) => i !== id));
  }

  let updateTodo = (todo, id)=>{
    localStorage.setItem('react-todo', JSON.stringify(todos.map((item, i) => i === id ? todo : item)));
    setTodos(todos.map((item, i) => i === id ? todo : item));
    closeForm()
  }
  let openEditForm = (todo, id) => {
    setFormEdit(true);
    setCurrentTodo({todo, id});
  }
  let closeForm = ()=>{
    setFormEdit(false);
  }
  return (
    <div className="App">

      <header className="App-header">
        <h1 className="title">TODO APP</h1>
      </header>

      <section className="todos-container">

        <AddTodo addTodo={addTodo}/>

        <div className="todos">
          {todos.length? todos.map((todo,i)=> <Todo todo={todo} i={i} key={i} deleteTodo={deleteTodo} openEditForm={openEditForm} />) : 'there are no todos yet'}
        </div>
        {isFormEditOpen && <EditTodo todo={currentTodo} closeForm={closeForm} updateTodo={updateTodo}/>}
      </section>
    </div>
  );
}

export default App;
